import {createSlice} from "@reduxjs/toolkit";

const initialState = {
	mainPosts: [
		{
			"id": 1,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 2,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		}, {
			"id": 3,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 4,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		}, {
			"id": 5,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 6,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		}, {
			"id": 7,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 8,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		}, {
			"id": 9,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 10,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		}, {
			"id": 11,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 12,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		}, {
			"id": 13,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 14,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		}, {
			"id": 15,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 16,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		}, {
			"id": 17,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 18,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		}, {
			"id": 19,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "프론트엔드 성능 최적화",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-01",
			"countOfComments": 3,
			"author": "baby_dev",
			"likes": 107,
		}, {
			"id": 20,
			"thumbnail": "https://velog.velcdn.com/images/jinnyl22/post/ae0053ec-8848-4c17-8ff2-74e898e20e39/image.jpeg",
			"title": "내가 보려고 만든 GIT 사용법",
			"content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore eum illum impedit inventore ipsam ipsum laborum laudantium, pariatur qui voluptate! Accusantium, aperiam consequuntur facilis neque officia rerum sunt vitae voluptatum!",
			"createdAt": "2023-05-03",
			"countOfComments": 1,
			"author": "john",
			"likes": 22,
		},
	],
};

const postSlice = createSlice({
	name: "post",
	initialState,
	reducers: {
		/* TODO: 포스트 관련 액션 처리 */
		addPost: (state, action) => {
		},
		removePost: (state, action) => {
		},
		loadPost: (state, action) => {
		},
	},
});

const {actions, reducer: postReducer} = postSlice;

export const {addPost, loadPost, removePost} = actions;

export default postReducer;
